### ISSUE TITLE
✅ 클린아키텍처 멀티모듈 설정

### ISSUE THREAD

**Issue by MinjungShin** [CheoCharm/MapZ-Android#1]
# Description
클린아키텍처를 위한 멀티모듈 설정

# Todo
- [x] app, presentation, domain, data, local, remote 모듈 설정
- [x] 각 모듈간의 의존성 설정
  - [x] app: presentation, domain, data, local, remote 모듈에 의존성
  - [x] presentation: domain 모듈에 의존성
  - [x] data: domain 모듈에 의존성
  - [x] local: data 모듈에 의존성
  - [x] remote: data 모듈에 의존성
- [x] 각 모듈에 필요한 dependencies 추가 및 삭제
- [x] app 모듈의 themes.xml, colors.xml 삭제
- [x] presentation 모듈에 themes.xml, colors.xml 생성 및 NoActionBar 적용

# ETC
