### ISSUE TITLE
✅ 위치 사용

### ISSUE THREAD

**Issue by Hyesung82** [CheoCharm/MapZ-Android#30]
# Description
위치 확인하기에서 사진에 위치 정보가 없으면 현재 위치를 사용

# Todo
- [x] 위치 권한 설정
- [x] 위치 권한이 있을 때 기본 위치는 현재 위치
- [x] 위치 권한이 없을 때 기본 위치는 대한민국
- [x] 마커 드래그 시 처리
- [x] 위치 확인하기 화면에서 하단 UI 높이만큼 카메라 아래로 이동
- [x] 위치 권한 허용 상태에서 위치 확인하기 화면 진입 후 위치 권한을 해제했을 때 처리
- [ ] 대표 이미지 선택 기능 구현

# ETC
위치 정보가 없는 경우 하단 사진 목록에 뜨는 주소 기본값 논의해볼 것
