### ISSUE TITLE
✅ MapZ 자동로그인 구현

### ISSUE THREAD

**Issue by MinjungShin** [CheoCharm/MapZ-Android#32]
# Description
MapZ 자동로그인 구현

# Todo
- [x] 자동로그인을 default로
- [x] SharedPreference에 자동로그인 여부 저장
- [x] 사용자가 앱을 실행했을 때 자동로그인 여부 체크하여 자동 로그인되도록
- [x] LocalDataSource, Repository, UseCase 구현

# ETC
