### ISSUE TITLE
✅ 상단바 색깔 설정

### ISSUE THREAD

**Issue by Hyesung82** [CheoCharm/MapZ-Android#40]
# Description
화면 별로 상단바 색깔 설정
[참고](https://stickode.tistory.com/464)

# Todo
- [ ] 홈 화면 상단바 투명하게 변경
- [x] 작성 - 그룹 선택 화면 상단바 빨간색으로 변경
- [x] 작성 - 사진 선택 화면 상단바 흰색으로 변경

# ETC
