### ISSUE TITLE
✅ 검색화면 구현

### ISSUE THREAD

**Issue by MinjungShin** [CheoCharm/MapZ-Android#44]
# Description
bottom navigation의 검색 화면 구현

# Todo
- [x] 검색화면, 검색결과, 그룹 썸넬, 그룹 가입하기 화면 디자인 구현
- [x] navigation 설정
- [x] 그룹 검색 API 사용하여 결과 보여주기
- [x] 그룹 가입 API 사용하여 그룹 가입하기
- [ ] 그룹 검색 결과 페이징 처리

# ETC
