### ISSUE TITLE
🐞 회원가입 에러사항들

### ISSUE THREAD

**Issue by MinjungShin** [CheoCharm/MapZ-Android#52]
# 문제 상황
회원가입에서 문제가 많다!

# 해결 방법
밑에 투두 참고

# Todo
- [ ] 회원가입할 때 정보동의화면에서 뒤로 갔다가 다시 회원가입하기 누르면 동의 체크했던 게 남아있음 -> ViewModel 생명주기를 아마..navGraph로
- [ ] 회원가입할 때 EditText에 작성한 텍스트가 뒤로가기 후 다시 돌아오면 사라져 있음
   onResume에서 EditText 값 ViewModel에서 읽어와서 넣어주기 또는 양방향 데이터 바인딩?!
- [ ] 스크롤로 인해 화면이 긴 경우에 뒤에 배경이 보임 -> 다음 버튼 부분 영역에 background white 주기, margin 더 늘리기
- [ ] 수정된 디자인에 따라 디자인 수정하기
- [ ] 인증번호 발급 부분 get 요청으로 수정

# ETC
