### ISSUE TITLE
✅ MapZ 회원가입

### ISSUE THREAD

**Issue by MinjungShin** [CheoCharm/MapZ-Android#6]
# Description
소셜로그인 외에 MapZ 회원가입 구현

# Todo
- [x] 회원가입 화면 구현
- [x] 비밀번호 유효성 검사
- [x] 닉네임 유효성 검사
- [x] 이메일 중복 검사 -> 서버에서 아마 인증번호 발급해줄 때 해줄듯..?
- [x] 회원가입에 성공하면 토스트 메시지 띄우고 로그인 화면으로 이동

# ETC
