### ISSUE TITLE
✅ 일기 작성하기 텍스트 편집 도구

### ISSUE THREAD

**Issue by Hyesung82** [CheoCharm/MapZ-Android#61]
# Description
일기 작성하기 화면 텍스트 편집 도구 구현

# Todo
- [x] 텍스트 색깔 선택 기능 구현
- [x] 글꼴 선택 기능 구현
- [x] 텍스트 정렬 기능 구현
- [x] 텍스트 볼드 설정 기능 구현
- [x] 텍스트 밑줄 설정 기능 구현
- [x] 스티커 삽입 기능 구현
- [x] 이미지 삽입 기능 구현

# ETC
이미지를 본문에 삽입하는 기능의 경우, 사진 크기 설정이나 드래그해서 이동하기는 어려울 듯함..
-> 차라리 인스타그램처럼 상단에 슬라이더로 구현하면 어떨지?
