### ISSUE TITLE
✅ 일기 작성하기 화면 커서 및 하이라이트 색깔 변경

### ISSUE THREAD

**Issue by Hyesung82** [CheoCharm/MapZ-Android#64]
# Description
일기 작성하기 화면 커서 및 하이라이트 색깔 변경

# Todo
- [ ] 제목 커서 색깔 변경
- [ ] 제목 하이라이트 색깔 변경
- [ ] 본문 커서 색깔 변경
- [ ] 본문 하이라이트 색깔 변경

# ETC
