### ISSUE TITLE
✅ 일기 작성하기 UI 글꼴 적용

### ISSUE THREAD

**Issue by Hyesung82** [CheoCharm/MapZ-Android#74]
# Description
UI 디자인에 따라 글꼴 적용

# Todo
- [x] 그룹 선택 화면
- [x] 사진 선택하기 화면
- [ ] 위치 확인하기 화면
- [ ] 일기 작성하기 화면

# ETC
다른 화면에도 잊지 말고 글꼴 적용할 것
